#!/bin/bash

#list dhcp address currently assigned"
#by the raspberry pi hotspot"
#20200225 km4ack

DHCP=$(cat /var/lib/misc/dnsmasq.leases)
HSS=$(cat /usr/bin/autohotspotN | grep "ip a add" | awk '{ print $4 }' | sed 's/\/24//')
CIP=$(ip address show dev wlan0 | grep -v inet6 | grep inet | awk '{ print $2 }' | sed 's/\/24//')
#CIP=$(ifconfig | grep -A 1 wlan0 | grep inet | awk '{ print $2 }')

if [ $HSS = $CIP ]
then
HSS=ACTIVATED
else
HSS=DEACTIVATED
fi

clear;echo;echo
echo "List of Current DHCP Addresses"
echo "$DHCP" | awk '{ print $3" "$4" "$5 }'
echo;echo
read -p "Flush DHCP Leases? y/n " ANS
if [ $HSS = 'ACTIVATED' ] && [ $ANS = 'y' ] || [ $ANS = 'Y' ]
then
cat <<EOF
Hotspot is currently active.
Please shutdown the hotspot
by connecting to a known SSID
and try flushing DHCP leases
again
EOF
sleep 5
exit 1
fi
if [ $ANS = 'y' ] || [ $ANS = 'Y' ]
then
sudo systemctl stop dnsmasq
echo "" | sudo tee /var/lib/misc/dnsmasq.leases
sudo systemctl start dnsmasq
echo "flushed"
sleep 2
fi

