#!/bin/bash

#main menu for hotspot tools
#20200221 km4ack

DIR=$HOME/hotspot-tools
VER=$(cat $DIR/changelog | grep version= | sed 's/version=//')

PS3='Please enter your choice: '
MAINMENU () {

HS=$(systemctl is-active autohotspot)
CURRENTNAME=$(sudo cat /etc/hostapd/hostapd.conf | grep ssid= | head -1 | sed 's/ssid=//')
CURRENTPASS=$(sudo cat /etc/hostapd/hostapd.conf | grep wpa_passphrase= | sed 's/wpa_passphrase=//')
HSIP=$(cat /usr/bin/autohotspotN | grep "ip a add" | sed 's/ip\ a\ add\ //' | sed 's/\/24.*$//' | tr -d " ")

if [ $HS = 'active' ]
then
HS=enabled
elif [ $HS = 'inactive' ]
then
HS=disabled
fi


clear;echo
echo "Hotspot Tools v"$VER" by KM4ACK"
echo 
echo "------HOTSPOT PARAMETERS------"
echo "   Status   "$HS
echo "   SSID     "$CURRENTNAME
echo "   Password "$CURRENTPASS
echo "   IP Addy  "$HSIP  
echo "------------------------------"
echo
options=("Change Name/Password" "Run Hotspot" "Disable Hotspot" "Enable Hotspot" "Manange IP" "Add WiFi" "Known SSIDs" "Update" "Exit")
select opt in "${options[@]}"
do
    case $opt in
        "Change Name/Password")
            $DIR/hotspotname
	    MAINMENU
            ;;
        "Run Hotspot")
	    if [ $HS = 'enabled' ];then
	    echo "Standby......"
	    sudo /usr/bin/autohotspotN
	    sleep 4
	    else
	    echo "Hotspot is disabled. Please enable and try again."
	    sleep 3
	    fi
	    MAINMENU
            ;;
        "Disable Hotspot")
            $DIR/disable
	    sleep 3
	    MAINMENU
            ;;
       "Enable Hotspot")
            $DIR/enable
	    sleep 3
	    MAINMENU
            ;;
       "Manange IP")
	    $DIR/manage-ip
	    MAINMENU
            ;;
       "Add WiFi")
            $DIR/wificonnect
	    MAINMENU
            ;;
       "Known SSIDs")
            $DIR/knowssid
	    MAINMENU
            ;;
       "Update")
	    echo "checking for updates"
            cd $DIR
	    git fetch --all
	    git reset --hard origin/dev
	    bash setup
	    echo "Please restart HotSpot-Tools script to see changes."
  	    sleep 2
	    MAINMENU
            ;;
        "Exit")
            exit 0
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
}

MAINMENU







