#!/bin/bash

#script to list known ssid's
#20200222

DIR=$HOME/hotspot-tools-lite
VER=$(cat $DIR/changelog | grep version= | sed 's/version=//')
HS=$(systemctl is-enabled autohotspot)
HSR=$(systemctl is-active autohotspot)
CURRENTNAME=$(sudo cat /etc/hostapd/hostapd.conf | grep ssid= | head -1 | sed 's/ssid=//')
CURRENTPASS=$(sudo cat /etc/hostapd/hostapd.conf | grep wpa_passphrase= | sed 's/wpa_passphrase=//')
HSIP=$(cat /usr/bin/autohotspotN | grep "ip a add" | sed 's/ip\ a\ add\ //' | sed 's/\/24.*$//' | tr -d " ")

if [ $HSR = 'inactive' ]
then
HS="STOPPED ($HS)"
else
HS="RUNNING ($HS)"
fi

clear;echo
echo "Hotspot Tools v"$VER" by KM4ACK"
echo 
echo "------HOTSPOT PARAMETERS------"
echo "   Status   "$HS
echo "   SSID     "$CURRENTNAME
echo "   Password "$CURRENTPASS
echo "   IP Addr  "$HSIP  
echo "------------------------------"

SSID=$(sudo cat /etc/wpa_supplicant/wpa_supplicant.conf | grep ssid= | sed 's/ssid="//' | sed 's/"//')
echo
echo "List of currently known SSID's"
echo
echo "$SSID" | tr -d "[:blank:]"
echo
read -n 1 -s -r -p "Press any key to continue"
