#!/bin/bash

if [ ! -f /usr/bin/autohotspotN.bkup ]
then
sudo cp /usr/bin/autohotspotN /usr/bin/autohotspotN.bkup
echo "backup created"
else
echo "hotspot backup already exists"
fi

if [ ! -f /etc/dnsmasq.conf.bkup ]
then
sudo cp /etc/dnsmasq.conf /etc/dnsmasq.conf.bkup
echo "backup created"
else
echo "dnsmasq backup already exists"
fi

clear

echo "What are the first two sets of numbers for"
echo "your network? ex 192.168"
read IP

echo "You entered "$IP
read -p "Is this correct? y/n/exit " ANS

if [ $ANS = 'y' ] || [ $ANS = 'Y' ]
then
#set new ip for autohotspotN
sudo cp /usr/bin/autohotspotN.bkup /usr/bin/autohotspotN
sudo sed -i "s/10.10.10.10/$IP.10.10/" /usr/bin/autohotspotN
#set new ip for dnsmasq.conf
sudo cp /etc/dnsmasq.conf.bkup /etc/dnsmasq.conf
sudo sed -i "s/dhcp-range=10.*$/dhcp-range=$IP.10.150,$IP.10.200,255.255.255.0,12h/" /etc/dnsmasq.conf
sudo sed -i "s/dhcp-option=3,10.10.10.10/dhcp-option=3,$IP.10.10/" /etc/dnsmasq.conf
sudo sed -i "s/address=\/email.com\/10.10.10.10/address=\/email.com\/$IP.10.10/" /etc/dnsmasq.conf
elif [ $ANS = 'exit' ] || [ $ANS = 'EXIT' ]
then
exit 0
else
exit 0
fi

echo "After connecting to your hotspot wifi"
echo "use IP address "$IP".10.10 in VNC to connect"
echo "Reboot required to apply changes"