#!/bin/bash

#setup script for hotspot tools

sudo apt -y install xterm

DIR=$HOME/hotspot-tools-lite

#move menu file to menu folder
#chmod all files
#remove this script
cd $DIR
chmod +x disable enable hotspot-menu hotspotname knowssid manage-ip wificonnect
#create symlink in bin folder to use in pi main menu
sudo ln -sf $DIR/hotspot-menu /usr/local/bin/Hotspot-Tools-Lite
#create symlink on desktop
ln -sf $DIR/hotspot-menu $HOME/Desktop/Hotspot-Tools-Lite

#create menu item for hotspot tools
cat > hotspot-tools-lite.desktop <<EOF
[Desktop Entry]
Name=Hotspot Tools Lite
GenericName=Tools to Manage AutoHotSpot
Comment=Tools to Manage AutoHotSpot
Exec=/usr/local/bin/Hotspot-Tools-Lite
Icon=/home/pi/hotspot-tools-lite/logo.png
Terminal=true
Type=Application
Categories=Network;HamRadio;
EOF

sudo mv $DIR/hotspot-tools-lite.desktop /usr/share/applications/

